[package]
name = "clawx"
version = "0.1.0"
edition = "2021"
authors = ["Jacob Machado"]

[dependencies]
num_enum = "0.5.7"
shrinkwraprs = "0.3.0"
thiserror = "1.0.37"
itertools = "0.10.5"

[features]
trace_execution = []